/* Generated By:JavaCC: Do not edit this line. ParserConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface ParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int LETTER = 54;
  /** RegularExpression Id. */
  int DIGIT = 55;
  /** RegularExpression Id. */
  int OCTALDIGIT = 56;
  /** RegularExpression Id. */
  int HEXDIGIT = 57;
  /** RegularExpression Id. */
  int EXTENDEDCHAR = 58;
  /** RegularExpression Id. */
  int OTHERCHAR = 59;
  /** RegularExpression Id. */
  int ESCAPE = 60;
  /** RegularExpression Id. */
  int NUMBER = 61;
  /** RegularExpression Id. */
  int PRINTINGCHAR = 62;
  /** RegularExpression Id. */
  int CHAR = 63;
  /** RegularExpression Id. */
  int TEXT = 64;
  /** RegularExpression Id. */
  int ID = 70;

  /** Lexical state. */
  int DEFAULT = 0;
  /** Lexical state. */
  int INCOMMENT = 1;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\u000b\"",
    "\"\\f\"",
    "\"array\"",
    "\"break\"",
    "\"by\"",
    "\"const\"",
    "\"else\"",
    "\"for\"",
    "\"if\"",
    "\"loop\"",
    "\"object\"",
    "\"of\"",
    "\"proc\"",
    "\"record\"",
    "\"ref\"",
    "\"return\"",
    "\"then\"",
    "\"to\"",
    "\"type\"",
    "\"until\"",
    "\"val\"",
    "\"var\"",
    "\"while\"",
    "\"=\"",
    "\">\"",
    "\"<\"",
    "\"!\"",
    "\":\"",
    "\";\"",
    "\",\"",
    "\".\"",
    "\"==\"",
    "\">=\"",
    "\"<=\"",
    "\"!=\"",
    "\"&&\"",
    "\"||\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"%\"",
    "\"^\"",
    "\"(\"",
    "\")\"",
    "\"{\"",
    "\"}\"",
    "\"[\"",
    "\"]\"",
    "<LETTER>",
    "<DIGIT>",
    "<OCTALDIGIT>",
    "<HEXDIGIT>",
    "<EXTENDEDCHAR>",
    "<OTHERCHAR>",
    "<ESCAPE>",
    "<NUMBER>",
    "<PRINTINGCHAR>",
    "<CHAR>",
    "<TEXT>",
    "<token of kind 65>",
    "\"(*\"",
    "\"(*\"",
    "\"*)\"",
    "<token of kind 69>",
    "<ID>",
  };

}
